version: "3.7"
services:  
    # airflow LocalExecutor
    postgres:
        image: "postgres:13"
        container_name: "postgres"
        environment:
        - POSTGRES_USER=airflow
        - POSTGRES_PASSWORD=airflow
        - POSTGRES_DB=hospital
        ports:
        - "5432:5432"
        volumes:
        - ./data/postgres:/var/lib/postgresql/data

    initdb:
        image: jh111/airflow-hadoop-spark:latest
        depends_on:
          - postgres
        command:
          bash -c "airflow db init && airflow users  create --role Admin --username admin --email admin --firstname admin --lastname admin --password admin"
        env_file:
          - airflow.env
        

    airflow-webserver:
        image: jh111/airflow-hadoop-spark:latest
        restart: always
        volumes:
            - ./dags:/home/airflow/dags #DAG folder
            - ./entry/entry_webserver.sh:/home/airflow/entry.sh
        ports:
            - "7777:7777"
        healthcheck:
          test: ["CMD-SHELL", "[ -f /home/airflow/airflow-webserver.pid ]"]
          interval: 30s
          timeout: 30s
          retries: 3
        entrypoint: sh /home/airflow/entry.sh
        depends_on: 
          - postgres
        env_file:
          - airflow.env
    
    airflow-scheduler:
        image: jh111/airflow-hadoop-spark:latest
        restart: always
        volumes:
            - ./dags:/home/airflow/dags #DAG folder
            - ./entry/entry_scheduler.sh:/home/airflow/entry.sh
        entrypoint: sh /home/airflow/entry.sh
        healthcheck:
          test: ["CMD-SHELL", "[ -f /home/airflow/airflow-scheduler.pid ]"]
          interval: 30s
          timeout: 30s
          retries: 3
        depends_on: 
          - postgres
        env_file:
          - airflow.env

    django:
        image: jh111/django:v4
        restart: always
        ports:
        - "8181:8181"
        command: bash -c "source /venv/bin/activate &&
                          python3 /venv/src/black-dashboard-django/manage.py makemigrations &&
                          python3 /venv/src/black-dashboard-django/manage.py migrate &&
                          python3 /venv/src/black-dashboard-django/manage.py runserver 0.0.0.0:8181"
        depends_on:
         - postgres
        volumes:
        - ./venv:/venv
                   
